(define (calc-num idx total)
  (cond ((or (= idx 0) (= idx total)) 1)
        (else (+ (calc-num (- idx 1) (- total 1)) (calc-num idx (- total 1))))
        ) )
(define (show-row idx n)
  (display (calc-num idx n) )
  (display " " )
  (cond ((< idx n) (show-row (+ idx 1) n)))
  )
(define (pascal n)
  (cond ((> n 0) (pascal (- n 1))) )
  (show-row 0 n)
  (display "\n")
  )
(pascal 15)

