(define (even? n) (= (remainder n 2) 0))
(define (double n) (+ n n))
(define (halve n) (/ n 2))
(define (mul-i a b)
  (display a)
  (display " ")
  (display b)
  (display " \n")
    (cond ((= b 1) a)
          ((even? b) (mul-i (double a) (halve b)))
          (else (+ a (mul-i (double a) (halve (- b 1)))))
          )
  )
(define (mul a b)
  (mul-i a b)
  )

(mul 11 7110)
