(define (even? n) (= (remainder n 2) 0))
(define (double n) (+ n n))
(define (halve n) (/ n 2))
(define (mul-i result a b)
  (display a)
  (display " ")
  (display b)
  (display " \n")
    (cond ((= b 1) (+ result a))
          ((even? b) (mul-i result (double a) (halve b)))
          (else (mul-i (+ result a) (double a) (halve (- b 1))))
          )
  )
(define (mul a b)
  (mul-i 0 a b)
  )

(mul 11 7110)
(mul 12 7113)
